id: DB6B1FF34
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:36:22+00:00'
last_modified: '2022-05-27T15:04:54.592773+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    6aa7:
      image_group_id: I1PD95909
      title: བསྒོམ་པའི་རིམ་པ།
      total_pages: 1902
      order: 64
      base_file: 6aa7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
